/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  RetrieveAnAddressParams,
  RetrieveAnAddressHeaders,
  RetrieveAnAddress200,
  UpdateAnAddressHeaders,
  UpdateAnAddressBody,
  UpdateAnAddress200,
} from "./chargebeeAPI.schemas";

export class ChargebeeAddressesResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * Retrieves an address resource for a subscription and the specified label.

 * @summary Retrieve an address
 */
  public async retrieveAnAddress(
    params: RetrieveAnAddressParams,
    headers?: RetrieveAnAddressHeaders,
  ): Promise<AxiosResponse<RetrieveAnAddress200>> {
    return this.axios.get(`/addresses`, {
      params,
      headers,
    });
  }

  /**
 * Adds or replaces the address for a subscription. If an address is already present for the specified label, it will be replaced otherwise new address is added with that label.

 * @summary Update an address
 */
  public async updateAnAddress(
    updateAnAddressBody: UpdateAnAddressBody,
    headers?: UpdateAnAddressHeaders,
  ): Promise<AxiosResponse<UpdateAnAddress200>> {
    return this.axios.post(`/addresses`, {
      headers,
      json: updateAnAddressBody,
    });
  }
}
