/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  RetrieveAnAttachedItemParams,
  RetrieveAnAttachedItemHeaders,
  RetrieveAnAttachedItem200,
  UpdateAnAttachedItemHeaders,
  UpdateAnAttachedItemBody,
  UpdateAnAttachedItem200,
  DeleteAnAttachedItemHeaders,
  DeleteAnAttachedItemBody,
  DeleteAnAttachedItem200,
} from "./chargebeeAPI.schemas";

export class ChargebeeAttachedItemsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * Retrieves details of an attached addon or a charge item.

 * @summary Retrieve an attached item 
 */
  public async retrieveAnAttachedItem(
    attachedItemId: string,
    params: RetrieveAnAttachedItemParams,
    headers?: RetrieveAnAttachedItemHeaders,
  ): Promise<AxiosResponse<RetrieveAnAttachedItem200>> {
    return this.axios.get(`/attached_items/${attachedItemId}`, {
      params,
      headers,
    });
  }

  /**
 * Updates an attached addon or a charge item for a plan.

 * @summary Update an attached item
 */
  public async updateAnAttachedItem(
    attachedItemId: string,
    updateAnAttachedItemBody: UpdateAnAttachedItemBody,
    headers?: UpdateAnAttachedItemHeaders,
  ): Promise<AxiosResponse<UpdateAnAttachedItem200>> {
    return this.axios.post(`/attached_items/${attachedItemId}`, {
      headers,
      json: updateAnAttachedItemBody,
    });
  }

  /**
 * Deletes an attached addon or a charge item.

 * @summary Delete an attached item
 */
  public async deleteAnAttachedItem(
    attachedItemId: string,
    deleteAnAttachedItemBody: DeleteAnAttachedItemBody,
    headers?: DeleteAnAttachedItemHeaders,
  ): Promise<AxiosResponse<DeleteAnAttachedItem200>> {
    return this.axios.post(`/attached_items/${attachedItemId}/delete`, {
      headers,
      json: deleteAnAttachedItemBody,
    });
  }
}
