/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  RetrieveCardForACustomerHeaders,
  RetrieveCardForACustomer200,
} from "./chargebeeAPI.schemas";

export class ChargebeeCardsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * #### Deprecated

This operation is obsoleted by the [Retrieve a payment source API](/docs/api/payment_sources#retrieve_a_payment_source).

Retrieves the credit card for the customer id.

 * @summary Retrieve card for a customer
 */
  public async retrieveCardForACustomer(
    customerId: string,
    headers?: RetrieveCardForACustomerHeaders,
  ): Promise<AxiosResponse<RetrieveCardForACustomer200>> {
    return this.axios.get(`/cards/${customerId}`, {
      headers,
    });
  }
}
