/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  TaxesCsvImportHeaders,
  TaxesCsvImportBody,
  TaxesCsvImport200,
} from "./chargebeeAPI.schemas";

export class ChargebeeCsvTaxRulesResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
   * @summary Taxes Csv import
   */
  public async taxesCsvImport(
    taxesCsvImportBody: TaxesCsvImportBody,
    headers?: TaxesCsvImportHeaders,
  ): Promise<AxiosResponse<TaxesCsvImport200>> {
    return this.axios.post(`/csv_tax_rules`, {
      headers,
      json: taxesCsvImportBody,
    });
  }
}
