/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  RetrieveTheMetaDataParams,
  RetrieveTheMetaDataHeaders,
  RetrieveTheMetaData200,
  ListCustomFieldConfigsParams,
  ListCustomFieldConfigsHeaders,
  ListCustomFieldConfigs200,
} from "./chargebeeAPI.schemas";

export class ChargebeeCustomFieldConfigsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * Retrieves meta data of specific custom field.

 * @summary Retrieve the meta data
 */
  public async retrieveTheMetaData(
    params: RetrieveTheMetaDataParams,
    headers?: RetrieveTheMetaDataHeaders,
  ): Promise<AxiosResponse<RetrieveTheMetaData200>> {
    return this.axios.get(`/custom_field_configs/retrieve`, {
      params,
      headers,
    });
  }

  /**
 * Retrieves the list of custom fields meta data.

 * @summary List custom field configs
 */
  public async listCustomFieldConfigs(
    params?: ListCustomFieldConfigsParams,
    headers?: ListCustomFieldConfigsHeaders,
  ): Promise<AxiosResponse<ListCustomFieldConfigs200>> {
    return this.axios.get(`/custom_field_configs`, {
      params,
      headers,
    });
  }
}
