/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  ListEventsParams,
  ListEventsHeaders,
  ListEvents200,
  RetrieveAnEventHeaders,
  RetrieveAnEvent200,
} from "./chargebeeAPI.schemas";

export class ChargebeeEventsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * Retrieves list of events.


 * @summary List events
 */
  public async listEvents(
    params?: ListEventsParams,
    headers?: ListEventsHeaders,
  ): Promise<AxiosResponse<ListEvents200>> {
    return this.axios.get(`/events`, {
      params,
      headers,
    });
  }

  /**
 * Retrieves a specific event identified by a unique event identifier.

**Note:** Only events that are less than 90 days old will be retrieved.

 * @summary Retrieve an event
 */
  public async retrieveAnEvent(
    eventId: string,
    headers?: RetrieveAnEventHeaders,
  ): Promise<AxiosResponse<RetrieveAnEvent200>> {
    return this.axios.get(`/events/${eventId}`, {
      headers,
    });
  }
}
