/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  RetrieveFullExportStatusParams,
  RetrieveFullExportStatusHeaders,
  RetrieveFullExportStatus200,
} from "./chargebeeAPI.schemas";

export class ChargebeeFullExportsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
   * @summary Retrieve Full Export Status
   */
  public async retrieveFullExportStatus(
    params: RetrieveFullExportStatusParams,
    headers?: RetrieveFullExportStatusHeaders,
  ): Promise<AxiosResponse<RetrieveFullExportStatus200>> {
    return this.axios.get(`/full_exports/status`, {
      params,
      headers,
    });
  }
}
