/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  RetrieveStoreSubscriptionHeaders,
  RetrieveStoreSubscriptionBody,
  RetrieveStoreSubscription200,
  ImportReceiptHeaders,
  ImportReceiptBody,
  ImportReceipt200,
  ImportSubscriptionWithoutReceiptHeaders,
  ImportSubscriptionWithoutReceiptBody,
  ImportSubscriptionWithoutReceipt200,
  ProcessPurchaseCommandHeaders,
  ProcessPurchaseCommandBody,
  ProcessPurchaseCommand200,
} from "./chargebeeAPI.schemas";

export class ChargebeeInAppSubscriptionsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * This API verifies the application id `{in_app_subscription_app_id}` and `receipt` then returns the subscription details associated with the purchase.

#### Path Parameter

in_app_subscription_app_id  
required, string  

The handle is created by Chargebee for your Apple App Store or Google Play Store app. It can be obtained from the Chargebee web app.

The following are instructions to obtain the value of the path parameter for the Apple App Store and Google Play Store.

* **Apple App Store** : To obtain the value for `{in_app_subscription_app_id}`, click **View Keys** within the **Sync Overview** page of the web app and use the value of generated **App ID** for this parameter. See detailed steps [here](https://www.chargebee.com/docs/1.0/mobile-app-store-product-iap.html#resource-id).
* **Google Play Store** : To obtain the value for `{in_app_subscription_app_id}`, click **Set up notifications** within the **Sync Overview** page of the web app and use the value of generated **App ID** for this parameter. See detailed steps [here](https://www.chargebee.com/docs/1.0/mobile-playstore-notifications.html#app-id).

 * @summary Retrieve store subscription
 */
  public async retrieveStoreSubscription(
    inAppSubscriptionAppId: string,
    retrieveStoreSubscriptionBody: RetrieveStoreSubscriptionBody,
    headers?: RetrieveStoreSubscriptionHeaders,
  ): Promise<AxiosResponse<RetrieveStoreSubscription200>> {
    return this.axios.post(
      `/in_app_subscriptions/${inAppSubscriptionAppId}/retrieve`,
      {
        headers,
        json: retrieveStoreSubscriptionBody,
      },
    );
  }

  /**
 * Verifies an Apple App Store or Google Play Store in-app purchase [receipt](https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/validating_receipts_with_the_app_store?language=objc#overview) and imports [subscriptions](/docs/api/subscriptions) for all historical purchases made by the customer.  
**Tip**
An `in_app_subscription` is created for every unique `original_transaction_id`. Apple creates `original_transaction_id` for every create, upgrade, or downgrade of the subscription. A receipt hardly contains more than 100 `original_transaction_id`s. If a receipt contains more than 100 `original_transaction_id`s, Chargebee creates all subscription records but this endpoint returns the first 100 records in the response.

CSV upload has a file size [limitation](https://www.chargebee.com/docs/mobile-app-store-product-iap.html#upload-in-app-receipts) that increases the processing time and the number of receipts. This API removes such limitations and allows you to import historical in-app subscription receipts.  
**Note** : This API verifies receipt or token through Apple or Google and then processes them via Chargebee. For bulk imports, limit API calls to **6** per minute (**10** seconds apart) to ensure successful subscription imports.  

Apple App Store {#app_store}
----------------------------

This section provides details of the Import Receipt operation performed for the Apple App Store. This API processes only the historical in-app transaction receipts.  
**Important**   

* [Integrate Chargebee](https://www.chargebee.com/docs/mobile-app-store-connect.html#connnect-with-your-chargebee-site) with your Apple App Store account using your shared secret from Apple.
* It is strongly recommended to use this endpoint to import historical in-app subscriptions only.
* You must [import Apple App Store products](https://www.chargebee.com/docs/2.0/mobile-app-store-product-iap.html#import-products) using Chargebee's user interface before importing receipts using this API.

Chargebee validates the `receipt` with Apple App Store and does the following once validation succeeds:

#### Subscriptions {#ir_apple_app_store_pcv2}

[Subscriptions](/docs/api/subscriptions) are imported as follows:

1. A subscription is imported for every unique value of the [original_transaction_id](https://developer.apple.com/documentation/appstorereceipts/original_transaction_id?language=objc) in the Apple receipt.  
   **Note** : This is not done for `original_transaction_id`s for which a subscription already exists in Chargebee.
2. Each subscription imported has the following attributes set:
   * `id` set to `original_transaction_id`.
   * `start_date` set to the earliest [purchase_date_ms](https://developer.apple.com/documentation/appstorereceipts/responsebody/latest_receipt_info?language=objc).
   * `current_term_start` set to latest [purchase_date_ms](https://developer.apple.com/documentation/appstorereceipts/responsebody/latest_receipt_info?language=objc).
   * `current_term_end` set to [expires_date_ms](https://developer.apple.com/documentation/appstorereceipts/responsebody/latest_receipt_info?language=objc) of the same `Latest_receipt_info` element with the latest `purchase_date_ms`.
   * `item_price_id` set to `product_id`.
   * `status` set to `in_trial` if there is only one element of [Latest_receipt_info](https://developer.apple.com/documentation/appstorereceipts/responsebody/latest_receipt_info?language=objc) with the `original_transaction_id` and the field `is_trial_period` is `true`, then consider the subscription is currently in trial. No invoices are created for this subscription.

#### Invoices for the subscription

[Invoices](/docs/api/invoices) are imported as follows:

1. An invoice is imported to Chargebee for every element of the array [Latest_receipt_info](https://developer.apple.com/documentation/appstorereceipts/responsebody/latest_receipt_info?language=objc) which has [is_trial_period](https://developer.apple.com/documentation/appstorereceipts/is_trial_period?language=objc) as `false`.
2. Each imported invoice has the `subscription_id` set to `original_transaction_id`.

#### Transactions for the invoices

A [transaction](/docs/api/transactions) is imported for each invoice with the following details:

1. `reference_number` set to the `transaction_id`.
2. `payment_method` set to `apple_store`.



Google Play Store {#app_store}
------------------------------

This section provides details of the Import Receipt operation performed for the Google Play Store. This API is used to process only the historical in-app purchase subscriptions.  
**Important**   

* [Integrate Chargebee](https://www.chargebee.com/docs/2.0/mobile-playstore-connect.html) with your Google Play Store account using your [service account credentials JSON](https://www.chargebee.com/docs/2.0/mobile-playstore-connect.html#generate-service-account-credentials-json).
* It is strongly recommended to use this endpoint to import historical in-app subscriptions only.
* It is recommended to pass only the latest purchase `token`. If any other purchase `token` is passed instead of the latest one, there is a possibility of returning incorrect transaction details. If an expired purchase `token` is passed, then it returns an error.
* The Google purchase token is [valid for 60 days](https://developer.android.com/google/play/billing/subscriptions#lifecycle) from the subscription purchase date. After the `token` expires, an API request to Google Developers API returns an error.

Chargebee validates the purchase `token` with Google Play Store and does the following once validation succeeds:

#### Subscriptions {#ir_google_play_store_pcv2}

* A [subscription](/docs/api/subscriptions) is imported for every unique purchase token if it is not linked to an existing purchase `token`( `linkedPurchaseToken` field in `SubscriptionsV2.get` API Response).

* Each subscription imported has the following attributes set:

  * `id` set to a unique identifier generated by Chargebee and mapped to the `token` and `latestOrderId` of the `SubscriptionPurchaseV2` object from Google response.

  * `start_date` set to the earliest `SubscriptionPurchaseV2.startTime`.

  * `current_term_start` set to latest `SubscriptionPurchaseV2.startTime`.

  * `current_term_end` set to `expiryTime` of the same `SubscriptionPurchaseV2` element with the latest purchase.

  * `item_price_id` set to the concatenation of `product[id]` and `priceCurrencyCode` from Google.

  * `status` set to `in_trial` if the free trial configuration is enabled in Google and the [monetization.subscriptions.basePlans.offers.State](https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions.basePlans.offers#State) is `Active` with a [SubscriptionOfferPhase.duration](https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions.basePlans.offers#subscriptionofferphase), then consider the subscription is currently in trial. No invoices are created for this subscription.

#### Invoices for the subscription

Invoices are imported as follows:

* An [invoice](/docs/api/invoices "https://apidocs.chargebee.com/docs/api/invoices?prod_cat_ver=2") is imported to Chargebee for every new subscription and renewal of an existing subscription using `latestOrderId`.

* Each imported invoice has the `subscription_id` set to a unique identifier generated by Chargebee and mapped to the `token` and `latestOrderId`.

#### Transactions for the invoices

A [transaction](/docs/api/transactions) is imported for each invoice with the following details:

* `transaction.reference_number` is set to the `latestOrderId`.

* `transaction.payment_method` is set to `play_store`.

Path Parameter {#path_param}
----------------------------

`{in_app_subscription_app_id}`: The handle created by Chargebee for your Apple App Store or Google Play Store app. It can be obtained from the Chargebee web app.

The following are instructions to obtain the value of the path parameter for the Apple App Store and Google Play Store.

* **Apple App Store** : To obtain the value for `{in_app_subscription_app_id}`, click **View Keys** within the **Sync Overview** page of the web app and use the value of generated **App ID** for this parameter. See detailed steps [here](https://www.chargebee.com/docs/1.0/mobile-app-store-product-iap.html#connection-keys_app-id).
* **Google Play Store** : To obtain the value for `{in_app_subscription_app_id}`, click **Set up notifications** within the **Sync Overview** page of the web app and use the value of generated **App ID** for this parameter. See detailed steps [here](https://www.chargebee.com/docs/1.0/mobile-playstore-notifications.html#app-id).




 * @summary Import Receipt
 */
  public async importReceipt(
    inAppSubscriptionAppId: string,
    importReceiptBody: ImportReceiptBody,
    headers?: ImportReceiptHeaders,
  ): Promise<AxiosResponse<ImportReceipt200>> {
    return this.axios.post(
      `/in_app_subscriptions/${inAppSubscriptionAppId}/import_receipt`,
      {
        headers,
        json: importReceiptBody,
      },
    );
  }

  /**
 * The Import Subscriptions endpoint is a Chargebee API that allows you to import historic In-App Subscriptions without using a valid Apple App Store receipt. This endpoint is useful if you do not have access to the receipt data which is required for the [Import Receipt](https://apidocs.chargebee.com/docs/api/in_app_subscriptions#import_receipt) API.

With this API, you can import subscriptions and corresponding invoices for historic In-App purchases. The API returns the [in-app-subscriptions object](https://apidocs.chargebee.com/docs/api/in_app_subscriptions#in_app_subscription_attributes) once the historic subscription is successfully imported into Chargebee.  
**Note** :  

* Subscriptions cannot be imported from the Google Play Store without a receipt or token. Therefore; Chargebee does not allow you to use this API for the Google Play Store.
* Enable V1 notifications in the Apple App Store for subscriptions created without receipts. Chargebee depends on receipt data to update subscription statuses. Apple's V2 notifications do not have receipt information; therefore, Chargebee cannot process V2 notifications for subscriptions imported without receipts. Learn more about [++app store notifications++](https://apidocs.chargebee.com/docs/api/in_app_purchase_events?prod_cat_ver=2#app_store_notifications) and [++notification URL configuration++](https://www.chargebee.com/docs/mobile-app-store-product-iap.html#connection-keys_notification-url).

### Apple App Store

This section provides details of the Import Subscription operation when performed for the Apple App Store. This API creates a historic subscription if the incoming subscription is unknown. For a known subscription, it creates an invoice for the mentioned period.  
**Important**

* [Integrate Chargebee](https://www.chargebee.com/docs/mobile-app-store-connect.html#connnect-with-your-chargebee-site) with your Apple App Store account using your shared secret from Apple.

* It is strongly recommended to use this endpoint to create a historic In-App subscription only.

* You must import App Store products using Chargebee's user interface before importing receipts using this API.

Chargebee validates the application ID with Apple App Store and does the following once validation succeeds:

#### Subscription

1. Import the subscription from the `latest_receipt_info` array from Apple and a new subscription is imported for the item-price.   
   **Note:** The subscription is not imported if it already exists in Chargebee but we will import the associated invoice using the subscription\[transaction_id\] in the payload.

2. Each subscription imported has the following attribute set:

   * `id` set to `subscription[id]` . This `subscription[id]` is `original_transaction_id` in the receipts.

   * `start_date` set to `subscription[start_date]`. You need to provide this information from the oldest `Latest_receipt_info.purchase_date_ms`.

   * `term_start` set to `subscription[term_start]`. You need to provide this information from the oldest `Latest_receipt_info.purchase_date_ms)`.

   * `term_end` set to `subscription[term_end]`. You need to provide this information from the oldest `Latest_receipt_info.expires_date_ms`.

   * `item_price_id` set to `subscription[product_id] + subscription[currency_code].` You need to provide this information from the `Latest_receipt_info.product_id`.

   * Chargebee records the subscription in a **Trial** state if the `is_trial_period` is `true`.

   * Chargebee records the subscription in a **Canceled** state if the `term_end` is less than the `System.currentTime()`.

#### Invoice for the subscription

1. The payment is recorded against the subscription invoice.

   * Imported invoice has the `subscription_id` set to `original_transaction_id`.

**Transactions for the invoice**

1. The associated transaction is updated with the following details:

   * The `transaction.reference_number` is set to the `transaction_id` of the payment.

   * The `transaction.payment_method` is set to `apple_store`.

#### Path Parameter

in_app_subscription_app_id  
required, string  

The handle created by Chargebee for your App Store app. It can be obtained from within the Chargebee web app.

To obtain the value of `in_app_subscription_app_id `for the Apple App Store, click **View Keys** within the **Sync Overview** page of the web app, and use the value of generated **App ID** for this parameter. See detailed steps [here](https://www.chargebee.com/docs/mobile-app-store-product-iap.html#connection-keys_app-id).

 * @summary Import Subscription Without Receipt
 */
  public async importSubscriptionWithoutReceipt(
    inAppSubscriptionAppId: string,
    importSubscriptionWithoutReceiptBody: ImportSubscriptionWithoutReceiptBody,
    headers?: ImportSubscriptionWithoutReceiptHeaders,
  ): Promise<AxiosResponse<ImportSubscriptionWithoutReceipt200>> {
    return this.axios.post(
      `/in_app_subscriptions/${inAppSubscriptionAppId}/import_subscription`,
      {
        headers,
        json: importSubscriptionWithoutReceiptBody,
      },
    );
  }

  /**
 * Verifies an in-app purchase made by your customer and creates a subscription in Chargebee.  
**Tip**

The recommended approach is to call this endpoint from the client-side app directly. However, if you are using this API to replace an existing direct integration with Apple or Google, then you may choose to call this API from the server-side.  
**Note:**   

if App Store or Play Store products have not been imported to Chargebee and this API is invoked, Chargebee will automatically create plans that correspond to the store product IDs. However, if historical subscriptions are to be imported using the [import receipt](https://apidocs.chargebee.com/docs/api/in_app_subscriptions#import_receipt) API, importing products is mandatory. [Learn more](https://www.chargebee.com/docs/mobile_subscriptions.html).  

Apple App Store {#app_store}
----------------------------

This section provides details of the Process Purchase Command operation when performed for the Apple App Store. This API processes only the latest in-app transaction on the receipt. Sync historical subscriptions into Chargebee using [bulk import](https://www.chargebee.com/docs/2.0/mobile-app-store-product-iap.html#import-in-app-purchase-receipts) of In-App Purchase receipts.  
**Important**   

* [Integrate Chargebee](https://www.chargebee.com/docs/mobile-app-store-connect.html#connnect-with-your-chargebee-site) with your Apple App Store account using your shared secret from Apple.
* It is strongly recommended to use this endpoint to notify Chargebee of **new** purchases only.
* For updates to existing subscriptions, we recommend that you configure Apple App Store to send server notifications to Chargebee.

Chargebee validates the `receipt` with Apple App Store and does the following once validation succeeds:

1. Look for [item_family.id](/docs/api/item_families?prod_cat_ver=2#item_family_id) that matches the value Apple-App-Store, and create such a product family if not found.
2. Look for [item.id](/docs/api/items?prod_cat_ver=2#item_id) that matches `product[id]` and if not found, create such a plan-item under the item family described in the previous step.
3. Look for [item_price.id](/docs/api/item_prices?prod_cat_ver=2#item_price_id) that matches the concatenation of `product[id]` and `product[currency_code]`, and if not found, create such an item price under the item described in the previous step.
4. Create/update a subscription:
   * If the receipt is for a new purchase, a new subscription is created for the plan-item price described in the previous step. The subscription has the following details:
     * `id` set to [original_transaction_id](https://developer.apple.com/documentation/appstorereceipts/original_transaction_id?language=objc)
     * `start_date` set to [responseBody.Latest_receipt_info.purchase_date_ms](https://developer.apple.com/documentation/appstorereceipts/responsebody/latest_receipt_info?language=objc)
     * `current_term_end` set to `responseBody.Latest_receipt_info.expires_date_ms`
   * Instead, if the receipt belongs to an existing subscription in Chargebee, it is updated to reflect the current state of the subscription at Apple.
5. The payment is recorded against the subscription invoice. The associated transaction is updated with the following details:
   * The [transaction.reference_number](/docs/api/transactions?prod_cat_ver=2#transaction_reference_number) is set to the [transaction_id](https://developer.apple.com/documentation/appstorereceipts/transaction_id?language=objc) of the payment.
* The [transaction.payment_method](/docs/api/transactions#transaction_payment_method) is set to `apple_pay`.  

Google Play Store {#app_store}
------------------------------

This section provides details of the Process Purchase Command operation when performed for the Google Play Store. This API processes only the latest in-app transaction using the purchase token.  
**Important**   

* [Integrate Chargebee](https://www.chargebee.com/docs/2.0/mobile-playstore-connect.html#chargebee-configuration) with your Google Play Store account using the service account credentials JSON.
* It is strongly recommended to use this endpoint to notify Chargebee of **new** purchases only.
* For updates to existing subscriptions, we recommend that you configure Chargebee to receive Google's server notifications through pub/sub topic. [Learn more](https://developer.android.com/google/play/billing/getting-ready#setup-pubsub).

Chargebee validates the purchase **token** with Google Play Store and does the following once validation succeeds:

1. Look for [item_family.id](/docs/api/item_families?prod_cat_ver=2#item_family_id) that matches the value `Google-Play-Store`, and create such a product family if not found.
2. Look for [item.id](/docs/api/items?prod_cat_ver=2#item_id) that matches `product[id]` and if not found, create such a [plan-item](/docs/api/items?prod_cat_ver=2#item_type) under the item family described in the previous step.
3. Look for [item_price.id](/docs/api/item_prices?prod_cat_ver=2#item_price_id) that matches the concatenation of `product[id]` and [priceCurrencyCode](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions?hl=en#SubscriptionPurchase.FIELDS.price_currency_code), and if not found, create such an item price under the item described in the previous step.
4. Create/update a subscription:
   * If this token is for a new purchase, a new subscription is created for the plan-item price described in the previous step. The subscription has the following details:
     * `id` set to unique identifier generated by Chargebee and mapped to **token** of the [SubscriptionPurchase](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions?hl=en) object from Google response.
     * `start_date` set to `SubscriptionPurchase.startTimeMillis`.
     * `current_term_end` set to `SubscriptionPurchase.expiryTimeMillis`.
   * Instead, if the token belongs to an existing subscription in Chargebee, it is updated to reflect the current state of the subscription at Google.
5. The payment is recorded against the subscription invoice. The associated transaction is updated with the following details:
   * The [transaction.reference_number](/docs/api/transactions?prod_cat_ver=2#transaction_reference_number) is set to the [orderId](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions?hl=en#SubscriptionPurchase.FIELDS.order_id) of the payment.
   * The [transaction.payment_method](/docs/api/transactions#transaction_payment_method) is set to `play_store`.

Path Parameter {#path_param_pcv2}
---------------------------------

`{in_app_subscription_app_id}`: The handle created by Chargebee for your Apple App Store or Google Play Store app. It can be obtained from the Chargebee web app.

The following are instructions to obtain the value of the path parameter for the Apple App Store and Google Play Store.

* **Apple App Store** : To obtain the value for `{in_app_subscription_app_id}`, click **View Keys** within the **Sync Overview** page of the web app and use the value of generated **App ID** for this parameter. See detailed steps [here](https://www.chargebee.com/docs/1.0/mobile-app-store-product-iap.html#resource-id).
* **Google Play Store** : To obtain the value for `{in_app_subscription_app_id}`, click **Set up notifications** within the **Sync Overview** page of the web app and use the value of generated **App ID** for this parameter. See detailed steps [here](https://www.chargebee.com/docs/1.0/mobile-playstore-notifications.html#app-id).




 * @summary Process Purchase Command
 */
  public async processPurchaseCommand(
    inAppSubscriptionAppId: string,
    processPurchaseCommandBody: ProcessPurchaseCommandBody,
    headers?: ProcessPurchaseCommandHeaders,
  ): Promise<AxiosResponse<ProcessPurchaseCommand200>> {
    return this.axios.post(
      `/in_app_subscriptions/${inAppSubscriptionAppId}/process_purchase_command`,
      {
        headers,
        json: processPurchaseCommandBody,
      },
    );
  }
}
