/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  OneTimePurchaseHeaders,
  OneTimePurchaseBody,
  OneTimePurchase200,
} from "./chargebeeAPI.schemas";

export class ChargebeeNonSubscriptionsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * This API is used to sync consumable, non-consumable, and non-renewing product payments in Chargebee.

 * @summary One Time Purchase
 */
  public async oneTimePurchase(
    nonSubscriptionAppId: string,
    oneTimePurchaseBody: OneTimePurchaseBody,
    headers?: OneTimePurchaseHeaders,
  ): Promise<AxiosResponse<OneTimePurchase200>> {
    return this.axios.post(
      `/non_subscriptions/${nonSubscriptionAppId}/one_time_purchase`,
      {
        headers,
        json: oneTimePurchaseBody,
      },
    );
  }
}
