/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  RetrieveAPaymentIntentHeaders,
  RetrieveAPaymentIntent200,
  UpdateAPaymentIntentHeaders,
  UpdateAPaymentIntentBody,
  UpdateAPaymentIntent200,
  CreateAPaymentIntentHeaders,
  CreateAPaymentIntentBody,
  CreateAPaymentIntent200,
} from "./chargebeeAPI.schemas";

export class ChargebeePaymentIntentsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * Retrieves the PaymentIntent resource.

 * @summary Retrieve a payment intent
 */
  public async retrieveAPaymentIntent(
    paymentIntentId: string,
    headers?: RetrieveAPaymentIntentHeaders,
  ): Promise<AxiosResponse<RetrieveAPaymentIntent200>> {
    return this.axios.get(`/payment_intents/${paymentIntentId}`, {
      headers,
    });
  }

  /**
 * Updating properties on a PaymentIntent object. All the subsequent 3DS transaction attempts will have the updated values.

 * @summary Update a payment intent
 */
  public async updateAPaymentIntent(
    paymentIntentId: string,
    updateAPaymentIntentBody: UpdateAPaymentIntentBody,
    headers?: UpdateAPaymentIntentHeaders,
  ): Promise<AxiosResponse<UpdateAPaymentIntent200>> {
    return this.axios.post(`/payment_intents/${paymentIntentId}`, {
      headers,
      json: updateAPaymentIntentBody,
    });
  }

  /**
 * Creates a PaymentIntent object. This is to be used with Chargebee.js API to complete the 3DS flow for new or stored cards.

While creating, specify the appropriate gateway account and amount. Exact amount can be estimated using our [Estimate API](/docs/api/estimates).

#### Customer resource lookup and creation {#customer_lookup}

When [customer[id]](/docs/api/payment_intents#create_a_payment_intent_customer_id) is provided for this operation, it is looked up by Chargebee, and if found, the payment_intent is created for it. If not found, a new customer resource is created with the ID provided, and the payment_intent is created.

##### Multiple business entities

If multiple [business entities](/docs/api/advanced-features#mbe) are created for the site, the customer resource lookup and creation happen within the [context](/docs/api/advanced-features#mbe-context) of the business entity [specified](/docs/api/advanced-features#mbe-header-main) in this API call. If no business entity is specified, the customer resource lookup is performed within the [site context](/docs/api/advanced-features#mbe-context), and if not found, the resource is created for the [default business entity](/docs/api/advanced-features#mbe-default-be) of the site.

 * @summary Create a payment intent
 */
  public async createAPaymentIntent(
    createAPaymentIntentBody: CreateAPaymentIntentBody,
    headers?: CreateAPaymentIntentHeaders,
  ): Promise<AxiosResponse<CreateAPaymentIntent200>> {
    return this.axios.post(`/payment_intents`, {
      headers,
      json: createAPaymentIntentBody,
    });
  }
}
