/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  RetrieveAPromotionalCreditHeaders,
  RetrieveAPromotionalCredit200,
  ListPromotionalCreditsParams,
  ListPromotionalCreditsHeaders,
  ListPromotionalCredits200,
  DeductPromotionalCreditsHeaders,
  DeductPromotionalCreditsBody,
  DeductPromotionalCredits200,
  SetPromotionalCreditsHeaders,
  SetPromotionalCreditsBody,
  SetPromotionalCredits200,
  AddPromotionalCreditsHeaders,
  AddPromotionalCreditsBody,
  AddPromotionalCredits200,
} from "./chargebeeAPI.schemas";

export class ChargebeePromotionalCreditsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * This endpoint retrieves the promotional credit based on the promotional credit id

 * @summary Retrieve a promotional credit
 */
  public async retrieveAPromotionalCredit(
    accountCreditId: string,
    headers?: RetrieveAPromotionalCreditHeaders,
  ): Promise<AxiosResponse<RetrieveAPromotionalCredit200>> {
    return this.axios.get(`/promotional_credits/${accountCreditId}`, {
      headers,
    });
  }

  /**
 * This endpoint lists the promotional credits set for a customer

 * @summary List promotional credits
 */
  public async listPromotionalCredits(
    params?: ListPromotionalCreditsParams,
    headers?: ListPromotionalCreditsHeaders,
  ): Promise<AxiosResponse<ListPromotionalCredits200>> {
    return this.axios.get(`/promotional_credits`, {
      params,
      headers,
    });
  }

  /**
 * This API call can be used to deduct promotional credits for a customer. [Learn more about Promotional Credits](https://www.chargebee.com/docs/2.0/credit-notes.html#creating-promotional-credits).

For example, if a customer has a credit balance of $20, if you pass the **amount** as $5, then the customer's credit balance would become $15.

If you do not pass any amount as the input parameter then, it will deduct the whole available amount from the credit balance.

 * @summary Deduct Promotional Credits
 */
  public async deductPromotionalCredits(
    deductPromotionalCreditsBody: DeductPromotionalCreditsBody,
    headers?: DeductPromotionalCreditsHeaders,
  ): Promise<AxiosResponse<DeductPromotionalCredits200>> {
    return this.axios.post(`/promotional_credits/deduct`, {
      headers,
      json: deductPromotionalCreditsBody,
    });
  }

  /**
 * This API call can be used to set the promotional credits balance of a customer. [Learn more about Promotional Credits](https://www.chargebee.com/docs/2.0/credit-notes.html#creating-promotional-credits).

For example, if a customer has a credit balance of $10 and if you would like to set the balance to $100, you could pass the **amount** as $100.

 * @summary Set Promotional Credits
 */
  public async setPromotionalCredits(
    setPromotionalCreditsBody: SetPromotionalCreditsBody,
    headers?: SetPromotionalCreditsHeaders,
  ): Promise<AxiosResponse<SetPromotionalCredits200>> {
    return this.axios.post(`/promotional_credits/set`, {
      headers,
      json: setPromotionalCreditsBody,
    });
  }

  /**
 * This API call can be used to add promotional credits to a customer. [Learn more about Promotional Credits](https://www.chargebee.com/docs/2.0/credit-notes.html#creating-promotional-credits).

For example, if a customer has credits of $10, if you pass the **amount** as $10, then the customer's credit balance would become $20.

 * @summary Add Promotional Credits
 */
  public async addPromotionalCredits(
    addPromotionalCreditsBody: AddPromotionalCreditsBody,
    headers?: AddPromotionalCreditsHeaders,
  ): Promise<AxiosResponse<AddPromotionalCredits200>> {
    return this.axios.post(`/promotional_credits/add`, {
      headers,
      json: addPromotionalCreditsBody,
    });
  }
}
