/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  RetrieveLatestMigrationDetailsParams,
  RetrieveLatestMigrationDetailsHeaders,
  RetrieveLatestMigrationDetails200,
} from "./chargebeeAPI.schemas";

export class ChargebeeResourceMigrationsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * Gets the last migration details.

 * @summary Retrieve latest migration details
 */
  public async retrieveLatestMigrationDetails(
    params: RetrieveLatestMigrationDetailsParams,
    headers?: RetrieveLatestMigrationDetailsHeaders,
  ): Promise<AxiosResponse<RetrieveLatestMigrationDetails200>> {
    return this.axios.get(`/resource_migrations/retrieve_latest`, {
      params,
      headers,
    });
  }
}
