/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  ListRsDataExportResourcesParams,
  ListRsDataExportResourcesHeaders,
  ListRsDataExportResources200,
} from "./chargebeeAPI.schemas";

export class ChargebeeRsDataExportResourcesResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * Retrieves Revenue story resources

 * @summary List rs data export resources
 */
  public async listRsDataExportResources(
    params?: ListRsDataExportResourcesParams,
    headers?: ListRsDataExportResourcesHeaders,
  ): Promise<AxiosResponse<ListRsDataExportResources200>> {
    return this.axios.get(`/rs_data_export_resources`, {
      params,
      headers,
    });
  }
}
