/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  ListSiteMigrationDetailsParams,
  ListSiteMigrationDetailsHeaders,
  ListSiteMigrationDetails200,
} from "./chargebeeAPI.schemas";

export class ChargebeeSiteMigrationDetailsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * This endpoint lists the site migration details.

 * @summary List site migration details
 */
  public async listSiteMigrationDetails(
    params?: ListSiteMigrationDetailsParams,
    headers?: ListSiteMigrationDetailsHeaders,
  ): Promise<AxiosResponse<ListSiteMigrationDetails200>> {
    return this.axios.get(`/site_migration_details`, {
      params,
      headers,
    });
  }
}
