/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  CreateUsingVaultTempTokenHeaders,
  CreateUsingVaultTempTokenBody,
  CreateUsingVaultTempToken200,
  CreateACardPaymentMethodTokenHeaders,
  CreateACardPaymentMethodTokenBody,
  CreateACardPaymentMethodToken200,
  RetrieveATokenHeaders,
  RetrieveAToken200,
} from "./chargebeeAPI.schemas";

export class ChargebeeTokensResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * Generate a token using the one time token created by payment gateways for any specific payment method.

 * @summary Create using vault temp token
 */
  public async createUsingVaultTempToken(
    createUsingVaultTempTokenBody: CreateUsingVaultTempTokenBody,
    headers?: CreateUsingVaultTempTokenHeaders,
  ): Promise<AxiosResponse<CreateUsingVaultTempToken200>> {
    return this.axios.post(`/tokens/create_using_temp_token`, {
      headers,
      json: createUsingVaultTempTokenBody,
    });
  }

  /**
 * Generate a token that holds card related information.

 * @summary Create a card payment method token
 */
  public async createACardPaymentMethodToken(
    createACardPaymentMethodTokenBody: CreateACardPaymentMethodTokenBody,
    headers?: CreateACardPaymentMethodTokenHeaders,
  ): Promise<AxiosResponse<CreateACardPaymentMethodToken200>> {
    return this.axios.post(`/tokens/create_for_card`, {
      headers,
      json: createACardPaymentMethodTokenBody,
    });
  }

  /**
 * Retrieve a token using token ID.

 * @summary Retrieve a token
 */
  public async retrieveAToken(
    cbTokenId: string,
    headers?: RetrieveATokenHeaders,
  ): Promise<AxiosResponse<RetrieveAToken200>> {
    return this.axios.get(`/tokens/${cbTokenId}`, {
      headers,
    });
  }
}
