/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  RetrieveUsagesForAnInvoiceAsPdfHeaders,
  RetrieveUsagesForAnInvoiceAsPdfBody,
  RetrieveUsagesForAnInvoiceAsPdf200,
  ListUsagesParams,
  ListUsagesHeaders,
  ListUsages200,
} from "./chargebeeAPI.schemas";

export class ChargebeeUsagesResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * Retrieves usages record for an invoice in PDF file format.

 * @summary Retrieve Usages for an Invoice as PDF
 */
  public async retrieveUsagesForAnInvoiceAsPdf(
    retrieveUsagesForAnInvoiceAsPdfBody: RetrieveUsagesForAnInvoiceAsPdfBody,
    headers?: RetrieveUsagesForAnInvoiceAsPdfHeaders,
  ): Promise<AxiosResponse<RetrieveUsagesForAnInvoiceAsPdf200>> {
    return this.axios.post(`/usages/pdf`, {
      headers,
      json: retrieveUsagesForAnInvoiceAsPdfBody,
    });
  }

  /**
 * Retrieves the list of usages.

 * @summary List usages
 */
  public async listUsages(
    params: ListUsagesParams,
    headers?: ListUsagesHeaders,
  ): Promise<AxiosResponse<ListUsages200>> {
    return this.axios.get(`/usages`, {
      params,
      headers,
    });
  }
}
