/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Chargebee API
 * OpenAPI spec version: v2 (PC 2.0)
 */
import type { AxiosInstance, AxiosResponse } from "axios";
import type {
  RetrieveAProductVariantHeaders,
  RetrieveAProductVariant200,
  UpdateAProductVariantHeaders,
  UpdateAProductVariantBody,
  UpdateAProductVariant200,
  DeleteAProductVariantHeaders,
  DeleteAProductVariant200,
} from "./chargebeeAPI.schemas";

export class ChargebeeVariantsResource {
  constructor(private readonly axios: AxiosInstance) {}

  /**
 * This API is used to retrieve a product variant using `variant_id`.

 * @summary Retrieve a product variant
 */
  public async retrieveAProductVariant(
    productVariantId: string,
    headers?: RetrieveAProductVariantHeaders,
  ): Promise<AxiosResponse<RetrieveAProductVariant200>> {
    return this.axios.get(`/variants/${productVariantId}`, {
      headers,
    });
  }

  /**
 * This API is used to modify a product variant.

 * @summary Update a product variant
 */
  public async updateAProductVariant(
    productVariantId: string,
    updateAProductVariantBody: UpdateAProductVariantBody,
    headers?: UpdateAProductVariantHeaders,
  ): Promise<AxiosResponse<UpdateAProductVariant200>> {
    return this.axios.post(`/variants/${productVariantId}`, {
      headers,
      json: updateAProductVariantBody,
    });
  }

  /**
 * This API deletes a product variant and returns the delete attribute value as `true`. Deletion of a product variant is not allowed if there are `active` or `archived` `item_price_id` under the variant. Once the variant is deleted, the `id` and `name` of the product variant can be reused.

 * @summary Delete a product variant
 */
  public async deleteAProductVariant(
    productVariantId: string,
    headers?: DeleteAProductVariantHeaders,
  ): Promise<AxiosResponse<DeleteAProductVariant200>> {
    return this.axios.post(`/variants/${productVariantId}/delete`, {
      headers,
    });
  }
}
